//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 3.4.1.9004
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// $ANTLR 3.4.1.9004 Simple.g 2012-09-29 18:09:58

// The variable 'variable' is assigned but its value is never used.
#pragma warning disable 219
// Unreachable code detected.
#pragma warning disable 162
// Missing XML comment for publicly visible type or member 'Type_or_Member'
#pragma warning disable 1591
// CLS compliance checking will not be performed on 'type' because it is not visible from outside this assembly.
#pragma warning disable 3019


using System.Collections.Generic;
using Antlr.Runtime;
using Antlr.Runtime.Misc;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "3.4.1.9004")]
[System.CLSCompliant(false)]
public partial class SimpleLexer : Antlr.Runtime.Lexer
{
	public const int EOF=-1;
	public const int DIGIT=4;
	public const int DIV=5;
	public const int IDENT=6;
	public const int LETTER=7;
	public const int MINUS=8;
	public const int MUL=9;
	public const int NUMBER=10;
	public const int PLUS=11;
	public const int PROGRAM=12;
	public const int STMT_ASSIGN=13;
	public const int STMT_INPUT=14;
	public const int STMT_PRINT=15;
	public const int WS=16;
	public const int T__17=17;
	public const int T__18=18;
	public const int T__19=19;
	public const int T__20=20;
	public const int T__21=21;
	public const int T__22=22;
	public const int T__23=23;

    // delegates
    // delegators

	public SimpleLexer()
	{
		OnCreated();
	}

	public SimpleLexer(ICharStream input )
		: this(input, new RecognizerSharedState())
	{
	}

	public SimpleLexer(ICharStream input, RecognizerSharedState state)
		: base(input, state)
	{

		OnCreated();
	}
	public override string GrammarFileName { get { return "Simple.g"; } }


	partial void OnCreated();
	partial void EnterRule(string ruleName, int ruleIndex);
	partial void LeaveRule(string ruleName, int ruleIndex);

	partial void EnterRule_DIV();
	partial void LeaveRule_DIV();

	// $ANTLR start "DIV"
	[GrammarRule("DIV")]
	private void mDIV()
	{
		EnterRule_DIV();
		EnterRule("DIV", 1);
		TraceIn("DIV", 1);
		try
		{
			int _type = DIV;
			int _channel = DefaultTokenChannel;
			// Simple.g:2:5: ( '/' )
			DebugEnterAlt(1);
			// Simple.g:2:7: '/'
			{
			DebugLocation(2, 7);
			Match('/'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("DIV", 1);
			LeaveRule("DIV", 1);
			LeaveRule_DIV();
		}
	}
	// $ANTLR end "DIV"

	partial void EnterRule_MINUS();
	partial void LeaveRule_MINUS();

	// $ANTLR start "MINUS"
	[GrammarRule("MINUS")]
	private void mMINUS()
	{
		EnterRule_MINUS();
		EnterRule("MINUS", 2);
		TraceIn("MINUS", 2);
		try
		{
			int _type = MINUS;
			int _channel = DefaultTokenChannel;
			// Simple.g:3:7: ( '-' )
			DebugEnterAlt(1);
			// Simple.g:3:9: '-'
			{
			DebugLocation(3, 9);
			Match('-'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("MINUS", 2);
			LeaveRule("MINUS", 2);
			LeaveRule_MINUS();
		}
	}
	// $ANTLR end "MINUS"

	partial void EnterRule_MUL();
	partial void LeaveRule_MUL();

	// $ANTLR start "MUL"
	[GrammarRule("MUL")]
	private void mMUL()
	{
		EnterRule_MUL();
		EnterRule("MUL", 3);
		TraceIn("MUL", 3);
		try
		{
			int _type = MUL;
			int _channel = DefaultTokenChannel;
			// Simple.g:4:5: ( '*' )
			DebugEnterAlt(1);
			// Simple.g:4:7: '*'
			{
			DebugLocation(4, 7);
			Match('*'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("MUL", 3);
			LeaveRule("MUL", 3);
			LeaveRule_MUL();
		}
	}
	// $ANTLR end "MUL"

	partial void EnterRule_PLUS();
	partial void LeaveRule_PLUS();

	// $ANTLR start "PLUS"
	[GrammarRule("PLUS")]
	private void mPLUS()
	{
		EnterRule_PLUS();
		EnterRule("PLUS", 4);
		TraceIn("PLUS", 4);
		try
		{
			int _type = PLUS;
			int _channel = DefaultTokenChannel;
			// Simple.g:5:6: ( '+' )
			DebugEnterAlt(1);
			// Simple.g:5:8: '+'
			{
			DebugLocation(5, 8);
			Match('+'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("PLUS", 4);
			LeaveRule("PLUS", 4);
			LeaveRule_PLUS();
		}
	}
	// $ANTLR end "PLUS"

	partial void EnterRule_T__17();
	partial void LeaveRule_T__17();

	// $ANTLR start "T__17"
	[GrammarRule("T__17")]
	private void mT__17()
	{
		EnterRule_T__17();
		EnterRule("T__17", 5);
		TraceIn("T__17", 5);
		try
		{
			int _type = T__17;
			int _channel = DefaultTokenChannel;
			// Simple.g:6:7: ( '(' )
			DebugEnterAlt(1);
			// Simple.g:6:9: '('
			{
			DebugLocation(6, 9);
			Match('('); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__17", 5);
			LeaveRule("T__17", 5);
			LeaveRule_T__17();
		}
	}
	// $ANTLR end "T__17"

	partial void EnterRule_T__18();
	partial void LeaveRule_T__18();

	// $ANTLR start "T__18"
	[GrammarRule("T__18")]
	private void mT__18()
	{
		EnterRule_T__18();
		EnterRule("T__18", 6);
		TraceIn("T__18", 6);
		try
		{
			int _type = T__18;
			int _channel = DefaultTokenChannel;
			// Simple.g:7:7: ( ')' )
			DebugEnterAlt(1);
			// Simple.g:7:9: ')'
			{
			DebugLocation(7, 9);
			Match(')'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__18", 6);
			LeaveRule("T__18", 6);
			LeaveRule_T__18();
		}
	}
	// $ANTLR end "T__18"

	partial void EnterRule_T__19();
	partial void LeaveRule_T__19();

	// $ANTLR start "T__19"
	[GrammarRule("T__19")]
	private void mT__19()
	{
		EnterRule_T__19();
		EnterRule("T__19", 7);
		TraceIn("T__19", 7);
		try
		{
			int _type = T__19;
			int _channel = DefaultTokenChannel;
			// Simple.g:8:7: ( ',' )
			DebugEnterAlt(1);
			// Simple.g:8:9: ','
			{
			DebugLocation(8, 9);
			Match(','); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__19", 7);
			LeaveRule("T__19", 7);
			LeaveRule_T__19();
		}
	}
	// $ANTLR end "T__19"

	partial void EnterRule_T__20();
	partial void LeaveRule_T__20();

	// $ANTLR start "T__20"
	[GrammarRule("T__20")]
	private void mT__20()
	{
		EnterRule_T__20();
		EnterRule("T__20", 8);
		TraceIn("T__20", 8);
		try
		{
			int _type = T__20;
			int _channel = DefaultTokenChannel;
			// Simple.g:9:7: ( ';' )
			DebugEnterAlt(1);
			// Simple.g:9:9: ';'
			{
			DebugLocation(9, 9);
			Match(';'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__20", 8);
			LeaveRule("T__20", 8);
			LeaveRule_T__20();
		}
	}
	// $ANTLR end "T__20"

	partial void EnterRule_T__21();
	partial void LeaveRule_T__21();

	// $ANTLR start "T__21"
	[GrammarRule("T__21")]
	private void mT__21()
	{
		EnterRule_T__21();
		EnterRule("T__21", 9);
		TraceIn("T__21", 9);
		try
		{
			int _type = T__21;
			int _channel = DefaultTokenChannel;
			// Simple.g:10:7: ( '=' )
			DebugEnterAlt(1);
			// Simple.g:10:9: '='
			{
			DebugLocation(10, 9);
			Match('='); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__21", 9);
			LeaveRule("T__21", 9);
			LeaveRule_T__21();
		}
	}
	// $ANTLR end "T__21"

	partial void EnterRule_T__22();
	partial void LeaveRule_T__22();

	// $ANTLR start "T__22"
	[GrammarRule("T__22")]
	private void mT__22()
	{
		EnterRule_T__22();
		EnterRule("T__22", 10);
		TraceIn("T__22", 10);
		try
		{
			int _type = T__22;
			int _channel = DefaultTokenChannel;
			// Simple.g:11:7: ( 'input' )
			DebugEnterAlt(1);
			// Simple.g:11:9: 'input'
			{
			DebugLocation(11, 9);
			Match("input"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__22", 10);
			LeaveRule("T__22", 10);
			LeaveRule_T__22();
		}
	}
	// $ANTLR end "T__22"

	partial void EnterRule_T__23();
	partial void LeaveRule_T__23();

	// $ANTLR start "T__23"
	[GrammarRule("T__23")]
	private void mT__23()
	{
		EnterRule_T__23();
		EnterRule("T__23", 11);
		TraceIn("T__23", 11);
		try
		{
			int _type = T__23;
			int _channel = DefaultTokenChannel;
			// Simple.g:12:7: ( 'print' )
			DebugEnterAlt(1);
			// Simple.g:12:9: 'print'
			{
			DebugLocation(12, 9);
			Match("print"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__23", 11);
			LeaveRule("T__23", 11);
			LeaveRule_T__23();
		}
	}
	// $ANTLR end "T__23"

	partial void EnterRule_NUMBER();
	partial void LeaveRule_NUMBER();

	// $ANTLR start "NUMBER"
	[GrammarRule("NUMBER")]
	private void mNUMBER()
	{
		EnterRule_NUMBER();
		EnterRule("NUMBER", 12);
		TraceIn("NUMBER", 12);
		try
		{
			int _type = NUMBER;
			int _channel = DefaultTokenChannel;
			// Simple.g:59:2: ( ( DIGIT )+ )
			DebugEnterAlt(1);
			// Simple.g:59:4: ( DIGIT )+
			{
			DebugLocation(59, 4);
			// Simple.g:59:4: ( DIGIT )+
			int cnt1=0;
			try { DebugEnterSubRule(1);
			while (true)
			{
				int alt1=2;
				try { DebugEnterDecision(1, false);
				int LA1_1 = input.LA(1);

				if (((LA1_1>='0' && LA1_1<='9')))
				{
					alt1 = 1;
				}


				} finally { DebugExitDecision(1); }
				switch (alt1)
				{
				case 1:
					DebugEnterAlt(1);
					// Simple.g:
					{
					DebugLocation(59, 4);
					input.Consume();


					}
					break;

				default:
					if (cnt1 >= 1)
						goto loop1;

					EarlyExitException eee1 = new EarlyExitException( 1, input );
					DebugRecognitionException(eee1);
					throw eee1;
				}
				cnt1++;
			}
			loop1:
				;

			} finally { DebugExitSubRule(1); }


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("NUMBER", 12);
			LeaveRule("NUMBER", 12);
			LeaveRule_NUMBER();
		}
	}
	// $ANTLR end "NUMBER"

	partial void EnterRule_IDENT();
	partial void LeaveRule_IDENT();

	// $ANTLR start "IDENT"
	[GrammarRule("IDENT")]
	private void mIDENT()
	{
		EnterRule_IDENT();
		EnterRule("IDENT", 13);
		TraceIn("IDENT", 13);
		try
		{
			int _type = IDENT;
			int _channel = DefaultTokenChannel;
			// Simple.g:63:2: ( ( LETTER | '_' ) ( LETTER | '_' | DIGIT )* )
			DebugEnterAlt(1);
			// Simple.g:63:4: ( LETTER | '_' ) ( LETTER | '_' | DIGIT )*
			{
			DebugLocation(63, 4);
			if ((input.LA(1)>='A' && input.LA(1)<='Z')||input.LA(1)=='_'||(input.LA(1)>='a' && input.LA(1)<='z'))
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}

			DebugLocation(63, 19);
			// Simple.g:63:19: ( LETTER | '_' | DIGIT )*
			try { DebugEnterSubRule(2);
			while (true)
			{
				int alt2=2;
				try { DebugEnterDecision(2, false);
				int LA2_1 = input.LA(1);

				if (((LA2_1>='0' && LA2_1<='9')||(LA2_1>='A' && LA2_1<='Z')||LA2_1=='_'||(LA2_1>='a' && LA2_1<='z')))
				{
					alt2 = 1;
				}


				} finally { DebugExitDecision(2); }
				switch ( alt2 )
				{
				case 1:
					DebugEnterAlt(1);
					// Simple.g:
					{
					DebugLocation(63, 19);
					input.Consume();


					}
					break;

				default:
					goto loop2;
				}
			}

			loop2:
				;

			} finally { DebugExitSubRule(2); }


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("IDENT", 13);
			LeaveRule("IDENT", 13);
			LeaveRule_IDENT();
		}
	}
	// $ANTLR end "IDENT"

	partial void EnterRule_LETTER();
	partial void LeaveRule_LETTER();

	// $ANTLR start "LETTER"
	[GrammarRule("LETTER")]
	private void mLETTER()
	{
		EnterRule_LETTER();
		EnterRule("LETTER", 14);
		TraceIn("LETTER", 14);
		try
		{
			// Simple.g:70:2: ( 'A' .. 'Z' | 'a' .. 'z' )
			DebugEnterAlt(1);
			// Simple.g:
			{
			DebugLocation(70, 2);
			if ((input.LA(1)>='A' && input.LA(1)<='Z')||(input.LA(1)>='a' && input.LA(1)<='z'))
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}


			}

		}
		finally
		{
			TraceOut("LETTER", 14);
			LeaveRule("LETTER", 14);
			LeaveRule_LETTER();
		}
	}
	// $ANTLR end "LETTER"

	partial void EnterRule_DIGIT();
	partial void LeaveRule_DIGIT();

	// $ANTLR start "DIGIT"
	[GrammarRule("DIGIT")]
	private void mDIGIT()
	{
		EnterRule_DIGIT();
		EnterRule("DIGIT", 15);
		TraceIn("DIGIT", 15);
		try
		{
			// Simple.g:75:2: ( '0' .. '9' )
			DebugEnterAlt(1);
			// Simple.g:
			{
			DebugLocation(75, 2);
			if ((input.LA(1)>='0' && input.LA(1)<='9'))
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}


			}

		}
		finally
		{
			TraceOut("DIGIT", 15);
			LeaveRule("DIGIT", 15);
			LeaveRule_DIGIT();
		}
	}
	// $ANTLR end "DIGIT"

	partial void EnterRule_WS();
	partial void LeaveRule_WS();

	// $ANTLR start "WS"
	[GrammarRule("WS")]
	private void mWS()
	{
		EnterRule_WS();
		EnterRule("WS", 16);
		TraceIn("WS", 16);
		try
		{
			int _type = WS;
			int _channel = DefaultTokenChannel;
			// Simple.g:78:2: ( ( '\\t' | ( '\\r' )? '\\n' | ' ' )+ )
			DebugEnterAlt(1);
			// Simple.g:78:4: ( '\\t' | ( '\\r' )? '\\n' | ' ' )+
			{
			DebugLocation(78, 4);
			// Simple.g:78:4: ( '\\t' | ( '\\r' )? '\\n' | ' ' )+
			int cnt4=0;
			try { DebugEnterSubRule(4);
			while (true)
			{
				int alt4=4;
				try { DebugEnterDecision(4, false);
				switch (input.LA(1))
				{
				case '\t':
					{
					alt4 = 1;
					}
					break;
				case '\n':
				case '\r':
					{
					alt4 = 2;
					}
					break;
				case ' ':
					{
					alt4 = 3;
					}
					break;
				}

				} finally { DebugExitDecision(4); }
				switch (alt4)
				{
				case 1:
					DebugEnterAlt(1);
					// Simple.g:78:5: '\\t'
					{
					DebugLocation(78, 5);
					Match('\t'); 

					}
					break;
				case 2:
					DebugEnterAlt(2);
					// Simple.g:78:12: ( '\\r' )? '\\n'
					{
					DebugLocation(78, 12);
					// Simple.g:78:12: ( '\\r' )?
					int alt3=2;
					try { DebugEnterSubRule(3);
					try { DebugEnterDecision(3, false);
					int LA3_1 = input.LA(1);

					if ((LA3_1=='\r'))
					{
						alt3 = 1;
					}
					} finally { DebugExitDecision(3); }
					switch (alt3)
					{
					case 1:
						DebugEnterAlt(1);
						// Simple.g:78:12: '\\r'
						{
						DebugLocation(78, 12);
						Match('\r'); 

						}
						break;

					}
					} finally { DebugExitSubRule(3); }

					DebugLocation(78, 18);
					Match('\n'); 

					}
					break;
				case 3:
					DebugEnterAlt(3);
					// Simple.g:78:25: ' '
					{
					DebugLocation(78, 25);
					Match(' '); 

					}
					break;

				default:
					if (cnt4 >= 1)
						goto loop4;

					EarlyExitException eee4 = new EarlyExitException( 4, input );
					DebugRecognitionException(eee4);
					throw eee4;
				}
				cnt4++;
			}
			loop4:
				;

			} finally { DebugExitSubRule(4); }

			DebugLocation(78, 31);
			 _channel = Hidden; 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("WS", 16);
			LeaveRule("WS", 16);
			LeaveRule_WS();
		}
	}
	// $ANTLR end "WS"

	public override void mTokens()
	{
		// Simple.g:1:8: ( DIV | MINUS | MUL | PLUS | T__17 | T__18 | T__19 | T__20 | T__21 | T__22 | T__23 | NUMBER | IDENT | WS )
		int alt5=14;
		try { DebugEnterDecision(5, false);
		switch (input.LA(1))
		{
		case '/':
			{
			alt5 = 1;
			}
			break;
		case '-':
			{
			alt5 = 2;
			}
			break;
		case '*':
			{
			alt5 = 3;
			}
			break;
		case '+':
			{
			alt5 = 4;
			}
			break;
		case '(':
			{
			alt5 = 5;
			}
			break;
		case ')':
			{
			alt5 = 6;
			}
			break;
		case ',':
			{
			alt5 = 7;
			}
			break;
		case ';':
			{
			alt5 = 8;
			}
			break;
		case '=':
			{
			alt5 = 9;
			}
			break;
		case 'i':
			{
			int LA5_2 = input.LA(2);

			if ((LA5_2=='n'))
			{
				int LA5_3 = input.LA(3);

				if ((LA5_3=='p'))
				{
					int LA5_4 = input.LA(4);

					if ((LA5_4=='u'))
					{
						int LA5_5 = input.LA(5);

						if ((LA5_5=='t'))
						{
							int LA5_6 = input.LA(6);

							if (((LA5_6>='0' && LA5_6<='9')||(LA5_6>='A' && LA5_6<='Z')||LA5_6=='_'||(LA5_6>='a' && LA5_6<='z')))
							{
								alt5 = 13;
							}
							else
							{
								alt5 = 10;
							}
						}
						else
						{
							alt5 = 13;
						}
					}
					else
					{
						alt5 = 13;
					}
				}
				else
				{
					alt5 = 13;
				}
			}
			else
			{
				alt5 = 13;
			}
			}
			break;
		case 'p':
			{
			int LA5_2 = input.LA(2);

			if ((LA5_2=='r'))
			{
				int LA5_3 = input.LA(3);

				if ((LA5_3=='i'))
				{
					int LA5_4 = input.LA(4);

					if ((LA5_4=='n'))
					{
						int LA5_5 = input.LA(5);

						if ((LA5_5=='t'))
						{
							int LA5_6 = input.LA(6);

							if (((LA5_6>='0' && LA5_6<='9')||(LA5_6>='A' && LA5_6<='Z')||LA5_6=='_'||(LA5_6>='a' && LA5_6<='z')))
							{
								alt5 = 13;
							}
							else
							{
								alt5 = 11;
							}
						}
						else
						{
							alt5 = 13;
						}
					}
					else
					{
						alt5 = 13;
					}
				}
				else
				{
					alt5 = 13;
				}
			}
			else
			{
				alt5 = 13;
			}
			}
			break;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
			{
			alt5 = 12;
			}
			break;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':
			{
			alt5 = 13;
			}
			break;
		case '\t':
		case '\n':
		case '\r':
		case ' ':
			{
			alt5 = 14;
			}
			break;
		default:
			{
				NoViableAltException nvae = new NoViableAltException("", 5, 0, input, 1);
				DebugRecognitionException(nvae);
				throw nvae;
			}
		}

		} finally { DebugExitDecision(5); }
		switch (alt5)
		{
		case 1:
			DebugEnterAlt(1);
			// Simple.g:1:10: DIV
			{
			DebugLocation(1, 10);
			mDIV(); 

			}
			break;
		case 2:
			DebugEnterAlt(2);
			// Simple.g:1:14: MINUS
			{
			DebugLocation(1, 14);
			mMINUS(); 

			}
			break;
		case 3:
			DebugEnterAlt(3);
			// Simple.g:1:20: MUL
			{
			DebugLocation(1, 20);
			mMUL(); 

			}
			break;
		case 4:
			DebugEnterAlt(4);
			// Simple.g:1:24: PLUS
			{
			DebugLocation(1, 24);
			mPLUS(); 

			}
			break;
		case 5:
			DebugEnterAlt(5);
			// Simple.g:1:29: T__17
			{
			DebugLocation(1, 29);
			mT__17(); 

			}
			break;
		case 6:
			DebugEnterAlt(6);
			// Simple.g:1:35: T__18
			{
			DebugLocation(1, 35);
			mT__18(); 

			}
			break;
		case 7:
			DebugEnterAlt(7);
			// Simple.g:1:41: T__19
			{
			DebugLocation(1, 41);
			mT__19(); 

			}
			break;
		case 8:
			DebugEnterAlt(8);
			// Simple.g:1:47: T__20
			{
			DebugLocation(1, 47);
			mT__20(); 

			}
			break;
		case 9:
			DebugEnterAlt(9);
			// Simple.g:1:53: T__21
			{
			DebugLocation(1, 53);
			mT__21(); 

			}
			break;
		case 10:
			DebugEnterAlt(10);
			// Simple.g:1:59: T__22
			{
			DebugLocation(1, 59);
			mT__22(); 

			}
			break;
		case 11:
			DebugEnterAlt(11);
			// Simple.g:1:65: T__23
			{
			DebugLocation(1, 65);
			mT__23(); 

			}
			break;
		case 12:
			DebugEnterAlt(12);
			// Simple.g:1:71: NUMBER
			{
			DebugLocation(1, 71);
			mNUMBER(); 

			}
			break;
		case 13:
			DebugEnterAlt(13);
			// Simple.g:1:78: IDENT
			{
			DebugLocation(1, 78);
			mIDENT(); 

			}
			break;
		case 14:
			DebugEnterAlt(14);
			// Simple.g:1:84: WS
			{
			DebugLocation(1, 84);
			mWS(); 

			}
			break;

		}

	}


	#region DFA

	protected override void InitDFAs()
	{
		base.InitDFAs();
	}

 
	#endregion

}
